In [1]:
import os
import pandas as pd
import numpy as np

In [2]:
path='Data'
files = [file for file in os.listdir(path) if not file.startswith('.')] # Ignore hidden files

bike_df = pd.DataFrame()

for file in files:
    bike_data = pd.read_csv(path+"/"+file)
    bike_df = pd.concat([bike_data, bike_df])

print(bike_df.shape)
print(bike_df.columns)

(12851412, 15)
Index(['tripduration', 'starttime', 'stoptime', 'start station id',
       'start station name', 'start station latitude',
       'start station longitude', 'end station id', 'end station name',
       'end station latitude', 'end station longitude', 'bikeid', 'usertype',
       'birth year', 'gender'],
      dtype='object')

In [3]:
bike_df.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,2013,2020-08-01 00:00:00.8790,2020-08-01 00:33:34.7260,3295.0,Central Park W & W 96 St,40.791270,-73.964839,3992.0,W 169 St & Fort Washington Ave,40.842842,-73.942125,19706,Customer,1998,1
1,7002,2020-08-01 00:00:01.5910,2020-08-01 01:56:44.0720,3144.0,E 81 St & Park Ave,40.776777,-73.959010,3671.0,E 81 St & 2 Ave,40.774779,-73.954275,37191,Subscriber,1966,1
2,155,2020-08-01 00:00:03.5810,2020-08-01 00:02:38.6340,387.0,Centre St & Chambers St,40.712733,-74.004607,387.0,Centre St & Chambers St,40.712733,-74.004607,42561,Customer,1969,0
3,2720,2020-08-01 00:00:05.0130,2020-08-01 00:45:25.3270,3080.0,S 4 St & Rodney St,40.709340,-73.956080,3364.0,Carroll St & 5 Ave,40.675162,-73.981483,41607,Subscriber,1990,1
4,2938,2020-08-01 00:00:05.9420,2020-08-01 00:49:03.9640,3510.0,Adam Clayton Powell Blvd & W 123 St,40.807832,-73.949373,3282.0,5 Ave & E 88 St,40.783070,-73.959390,36366,Customer,1969,0

In [4]:
bike_df = bike_df.rename(columns={"tripduration": "Trip Duration",
                                            "starttime": "Start Time",
                                            "stoptime": "Stop Time",
                                            "start station id": "Start Station ID",
                                            "start station name": "Start Station Name",
                                            "start station latitude": "Start Station Lat",
                                            "start station longitude": "Start Station Lon",
                                            "end station id": "End Station ID",
                                            "end station name": "End Station Name",
                                            "end station latitude": "End Station Lat",
                                            "end station longitude": "End Station Lon",
                                            "bikeid": "Bike ID",
                                            "usertype": "User Type",
                                            "birth year": "Birth Year",
                                            "gender": "Gender"
                                           })
bike_df.head()

,Trip Duration,Start Time,Stop Time,Start Station ID,Start Station Name,Start Station Lat,Start Station Lon,End Station ID,End Station Name,End Station Lat,End Station Lon,Bike ID,User Type,Birth Year,Gender
0,2013,2020-08-01 00:00:00.8790,2020-08-01 00:33:34.7260,3295.0,Central Park W & W 96 St,40.791270,-73.964839,3992.0,W 169 St & Fort Washington Ave,40.842842,-73.942125,19706,Customer,1998,1
1,7002,2020-08-01 00:00:01.5910,2020-08-01 01:56:44.0720,3144.0,E 81 St & Park Ave,40.776777,-73.959010,3671.0,E 81 St & 2 Ave,40.774779,-73.954275,37191,Subscriber,1966,1
2,155,2020-08-01 00:00:03.5810,2020-08-01 00:02:38.6340,387.0,Centre St & Chambers St,40.712733,-74.004607,387.0,Centre St & Chambers St,40.712733,-74.004607,42561,Customer,1969,0
3,2720,2020-08-01 00:00:05.0130,2020-08-01 00:45:25.3270,3080.0,S 4 St & Rodney St,40.709340,-73.956080,3364.0,Carroll St & 5 Ave,40.675162,-73.981483,41607,Subscriber,1990,1
4,2938,2020-08-01 00:00:05.9420,2020-08-01 00:49:03.9640,3510.0,Adam Clayton Powell Blvd & W 123 St,40.807832,-73.949373,3282.0,5 Ave & E 88 St,40.783070,-73.959390,36366,Customer,1969,0

In [5]:
bike_df.dtypes

Trip Duration           int64
Start Time             object
Stop Time              object
Start Station ID      float64
Start Station Name     object
Start Station Lat     float64
Start Station Lon     float64
End Station ID        float64
End Station Name       object
End Station Lat       float64
End Station Lon       float64
Bike ID                 int64
User Type              object
Birth Year              int64
Gender                  int64
dtype: object

In [6]:
bike_df['Birth Year'].min()

1873

In [7]:
bike_df['Birth Year'].value_counts

<bound method IndexOpsMixin.value_counts of 0          1998
1          1966
2          1969
3          1990
4          1969
           ...
1913620    1969
1913621    1995
1913622    1985
1913623    1989
1913624    1974
Name: Birth Year, Length: 12851412, dtype: int64>

In [8]:
bike_df['Birth Year'].max()

2004

In [9]:
age_filt = bike_df['Birth Year'] <= 1920

In [10]:
bike_df = bike_df[~age_filt]

In [11]:
bike_df.shape

(12844947, 15)

In [12]:
filt_1940 = bike_df['Birth Year'] <= 1950

In [13]:
bike_df[filt_1940]

,Trip Duration,Start Time,Stop Time,Start Station ID,Start Station Name,Start Station Lat,Start Station Lon,End Station ID,End Station Name,End Station Lat,End Station Lon,Bike ID,User Type,Birth Year,Gender
247,89,2020-08-01 00:07:09.5500,2020-08-01 00:08:38.9170,289.0,Monroe St & Classon Ave,40.684568,-73.958811,120.0,Lexington Ave & Classon Ave,40.686768,-73.959282,15315,Subscriber,1938,2
630,511,2020-08-01 00:19:26.7140,2020-08-01 00:27:58.1630,3125.0,45 Rd & 11 St,40.747086,-73.949772,3615.0,44 Dr & 21 St,40.748000,-73.946093,32201,Subscriber,1946,2
677,608,2020-08-01 00:20:53.5150,2020-08-01 00:31:01.5770,289.0,Monroe St & Classon Ave,40.684568,-73.958811,120.0,Lexington Ave & Classon Ave,40.686768,-73.959282,40477,Subscriber,1938,2
696,305,2020-08-01 00:21:25.9030,2020-08-01 00:26:31.7900,3178.0,Riverside Dr & W 78 St,40.784145,-73.983625,3167.0,Amsterdam Ave & W 73 St,40.779668,-73.980930,40097,Subscriber,1950,1
962,102,2020-08-01 00:31:07.0570,2020-08-01 00:32:49.2690,120.0,Lexington Ave & Classon Ave,40.686768,-73.959282,289.0,Monroe St & Classon Ave,40.684568,-73.958811,40477,Subscriber,1938,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1913102,867,2018-07-30 20:23:10.1020,2018-07-30 20:37:37.1320,3695.0,E 5 St & 2 Ave,40.726870,-73.989190,433.0,E 13 St & Avenue A,40.729554,-73.980572,28755,Subscriber,1946,1
1913170,540,2018-07-31 11:31:41.5210,2018-07-31 11:40:41.5670,3695.0,E 5 St & 2 Ave,40.726870,-73.989190,380.0,W 4 St & 7 Ave S,40.734011,-74.002939,30672,Subscriber,1942,1
1913478,764,2018-07-30 18:28:42.7390,2018-07-30 18:41:27.4640,3697.0,W 64 St & Thelonious Monk Circle,40.775160,-73.989187,2023.0,E 55 St & Lexington Ave,40.759681,-73.970314,21143,Subscriber,1947,1
1913504,1863,2018-07-30 22:38:16.5720,2018-07-30 23:09:20.4040,3697.0,W 64 St & Thelonious Monk Circle,40.775160,-73.989187,3244.0,University Pl & E 8 St,40.731437,-73.994903,28093,Subscriber,1941,1
1913577,340,2018-07-31 16:33:13.6480,2018-07-31 16:38:53.7880,3697.0,W 64 St & Thelonious Monk Circle,40.775160,-73.989187,508.0,W 46 St & 11 Ave,40.763414,-73.996674,30904,Subscriber,1948,1

In [14]:
bike_df['Age'] = bike_df['Birth Year'].apply(lambda x: 2020 - x)
bike_df.head()

,Trip Duration,Start Time,Stop Time,Start Station ID,Start Station Name,Start Station Lat,Start Station Lon,End Station ID,End Station Name,End Station Lat,End Station Lon,Bike ID,User Type,Birth Year,Gender,Age
0,2013,2020-08-01 00:00:00.8790,2020-08-01 00:33:34.7260,3295.0,Central Park W & W 96 St,40.791270,-73.964839,3992.0,W 169 St & Fort Washington Ave,40.842842,-73.942125,19706,Customer,1998,1,22
1,7002,2020-08-01 00:00:01.5910,2020-08-01 01:56:44.0720,3144.0,E 81 St & Park Ave,40.776777,-73.959010,3671.0,E 81 St & 2 Ave,40.774779,-73.954275,37191,Subscriber,1966,1,54
2,155,2020-08-01 00:00:03.5810,2020-08-01 00:02:38.6340,387.0,Centre St & Chambers St,40.712733,-74.004607,387.0,Centre St & Chambers St,40.712733,-74.004607,42561,Customer,1969,0,51
3,2720,2020-08-01 00:00:05.0130,2020-08-01 00:45:25.3270,3080.0,S 4 St & Rodney St,40.709340,-73.956080,3364.0,Carroll St & 5 Ave,40.675162,-73.981483,41607,Subscriber,1990,1,30
4,2938,2020-08-01 00:00:05.9420,2020-08-01 00:49:03.9640,3510.0,Adam Clayton Powell Blvd & W 123 St,40.807832,-73.949373,3282.0,5 Ave & E 88 St,40.783070,-73.959390,36366,Customer,1969,0,51

In [15]:
bike_df.to_csv("Out/citi_bike.csv", index=False, header=True)